/*
 * Copyright 2026 ISA Research Group, Universidad de Sevilla.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.restest.core.execution;

import java.util.Objects;

/**
 * Where one chosen value came from.
 *
 * <p>ADR-0006 promises that every run persists "the provenance of each parameter value"; this is
 * that promise as a type. A {@link TestCase} is a concrete, already-decided attempt - one value per
 * parameter, not a distribution of candidates - so provenance answers one question per value: which
 * of the three things that can produce a value produced this one.
 *
 * <p>The three cases are the whole of what a value can be, and the amendment to ADR-0005 explains
 * why each is shaped the way it is. In short:
 *
 * <ul>
 *   <li>{@link Declared} - taken from the schema's own default or enumeration
 *       ({@link io.restest.core.schema.SchemaMetadata}), stated by the document itself.</li>
 *   <li>{@link Generated} - produced by whichever stateless mechanism was tried: a random provider,
 *       a boundary walk, a value dictionary, an external provider. {@code source} is an open name
 *       rather than an enumerated set, because none of those mechanisms exist yet in {@code core}
 *       and ADR-0008 forbids naming them here even once they do.</li>
 *   <li>{@link Derived} - read out of an earlier interaction's response, which is what makes a
 *       stateful step representable: "the {@code petId} for this request is the {@code id} the
 *       server returned when we created the pet."</li>
 * </ul>
 *
 * <p>Which of the three wins for a given parameter, in a given run, is a generation-time decision -
 * M1.5's value-provider chain and M4.2's runtime resource pool and value-source selection - and
 * belongs to {@code restest-gen}, not here. This type only has to be able to name the winner
 * afterwards.
 *
 * <p>Sealed, so that a report or a metrics collector counting values by origin fails to compile
 * rather than silently miscounting the day a fourth case is added:
 *
 * {@snippet :
 * String describe(ValueOrigin origin) {
 *     return switch (origin) {
 *         case ValueOrigin.Declared ignored -> "from the specification";
 *         case ValueOrigin.Generated g -> "generated by " + g.source();
 *         case ValueOrigin.Derived d -> "derived from " + d.from();
 *     };
 * }
 * }
 */
public sealed interface ValueOrigin {

    /** A value taken straight from the schema's own default or enumeration. */
    ValueOrigin DECLARED = new Declared();

    /** Taken from the schema's own default or enumeration. A record with no components: all instances are equal. */
    record Declared() implements ValueOrigin {
    }

    /**
     * Produced by a stateless generation mechanism.
     *
     * @param source what produced it, in a form fit to print in a report - a provider's own name,
     *     not a class name. Open-ended: {@code core} does not enumerate generation mechanisms
     */
    record Generated(String source) implements ValueOrigin {
        public Generated {
            Objects.requireNonNull(source, "source");
            if (source.isBlank()) {
                throw new IllegalArgumentException("a generated value must name what generated it");
            }
        }
    }

    /**
     * Read out of an earlier interaction's response - the mechanism that makes a stateful step
     * representable at all.
     *
     * <p>{@code from} names an {@link InteractionId}, not a {@link TestCaseId}, and this is not a
     * limitation: by the time a stateful generator can construct this value at all, the interaction
     * it depends on already exists and has already been read. {@link TestCase} holds concrete,
     * already-resolved values - never a placeholder to fill in later, per ADR-0005 - so a
     * {@code ParameterValue} carrying {@code Derived} can only be built once its {@code value()} is
     * known, which means the earlier interaction's response has already been inspected to produce
     * it. There is no earlier moment at which this edge would need to be committed to, and therefore
     * nothing gained by pointing at an identifier, such as {@link TestCaseId}, that exists sooner: an
     * {@link InteractionId} names exactly the interaction whose data was actually used, which is
     * unaffected by whatever the engine does afterwards with the test case that produced it - a
     * retry, a replay, or nothing at all.
     *
     * @param from the interaction this value was read from
     * @param description what was taken from it, for a human to read - "response body field 'id'" -
     *     not a parseable expression. The extraction grammar a stateful generator actually uses (a
     *     JSONPath, an OpenAPI {@code links} runtime expression, whatever the operation dependency
     *     graph infers) is M4.1-4.3's decision, none of which exist yet; committing to one now would
     *     mean guessing at a design several milestones away
     */
    record Derived(InteractionId from, String description) implements ValueOrigin {
        public Derived {
            Objects.requireNonNull(from, "from");
            Objects.requireNonNull(description, "description");
            if (description.isBlank()) {
                throw new IllegalArgumentException(
                        "a derived value must say what was taken from " + from);
            }
        }
    }
}
