/*
 * Copyright 2026 ISA Research Group, Universidad de Sevilla.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.restest.core.execution;

import java.util.Objects;
import java.util.Optional;

/**
 * Where one specific value used in a test came from.
 *
 * <p>RESTest keeps track of how every value it sends was chosen, so that a report or a person
 * reading it later can tell whether a value came straight from the API's own documentation, was
 * produced by a generator, or was taken from a previous request's response. A {@link TestCase} is a
 * concrete, already-decided attempt - one specific value per input, not a range of possibilities -
 * so this answers one simple question about each value: which of three things produced it.
 *
 * <ul>
 *   <li>{@link Declared} - taken directly from the API's own specification: a default value, one
 *       of a fixed list of choices it declares, or a sample value its author wrote down. Which of
 *       the three is named, so that "did the document's own samples help?" is a question a finished
 *       run can answer.</li>
 *   <li>{@link Generated} - produced by RESTest itself, using whichever technique was tried: a
 *       random value, a boundary case, a value picked from a dictionary, or a value supplied by an
 *       external source. {@code source} names that technique in plain text rather than from a fixed
 *       list, since RESTest is designed to support new techniques being added later.</li>
 *   <li>{@link Derived} - read out of an earlier request's response. This is what makes it possible
 *       to test a sequence of related requests: "the {@code petId} used in this request is the
 *       {@code id} the server returned when we created the pet."</li>
 * </ul>
 *
 * <p>Deciding which of the three applies to a given value, in a given run, is a decision made while
 * building the test case, elsewhere in RESTest. This type only has to be able to name, afterwards,
 * which one won.
 *
 * <p>These three are the only possibilities, which is enforced by the compiler: any code that
 * handles values by their origin must handle all three cases, or it will not compile, rather than
 * silently ignoring a case that gets added later:
 *
 * {@snippet :
 * String describe(ValueOrigin origin) {
 *     return switch (origin) {
 *         case ValueOrigin.Declared declared -> "the document stated it: " + declared.statement();
 *         case ValueOrigin.Generated g -> "generated by " + g.source();
 *         case ValueOrigin.Derived d -> "derived from " + d.from();
 *     };
 * }
 * }
 */
public sealed interface ValueOrigin {

    /**
     * A value the document stated, without saying which of the things it states produced it.
     *
     * <p>This is what a run recorded before RESTest kept that distinction reads back as. Nothing
     * generating values produces it any more: every source names the statement it read.
     */
    ValueOrigin DECLARED = new Declared(Optional.empty());

    /**
     * Taken from something the document itself states about the value.
     *
     * @param statement which of the things a document can state produced it, or nothing at all for
     *     a run recorded before RESTest kept them apart
     */
    record Declared(Optional<Statement> statement) implements ValueOrigin {

        public Declared {
            Objects.requireNonNull(statement, "statement");
        }

        /**
         * The three ways a document can hand us a concrete value.
         *
         * <p>They are worth telling apart because they are not equally good inputs, and because a
         * finished run should be able to say which of them earned its keep. Comparing the value
         * against the schema afterwards cannot answer that: a document whose default is also one of
         * its allowed values - {@code default: available} among {@code [available, pending, sold]},
         * which is the usual shape - leaves two of these indistinguishable.
         */
        public enum Statement {
            /** The value the API uses when the caller sends none. */
            DEFAULT,
            /** One of the fixed set of values the API accepts. */
            ENUMERATION,
            /** A sample value the document's author wrote down to show what a real one looks like. */
            EXAMPLE
        }
    }

    /**
     * A value taken from the named thing the document states about it.
     *
     * @param statement which of the things a document can state produced it
     * @return the origin
     */
    static Declared declared(Declared.Statement statement) {
        return new Declared(Optional.of(Objects.requireNonNull(statement, "statement")));
    }

    /**
     * Produced by a stateless generation mechanism.
     *
     * @param source what produced it, in a form fit to print in a report - a provider's own name,
     *     not a class name. Open-ended: {@code core} does not enumerate generation mechanisms
     */
    record Generated(String source) implements ValueOrigin {
        public Generated {
            Objects.requireNonNull(source, "source");
            if (source.isBlank()) {
                throw new IllegalArgumentException("a generated value must name what generated it");
            }
        }
    }

    /**
     * A value read out of an earlier interaction's response - the mechanism that makes a "stateful"
     * step (one that depends on an earlier request) possible at all.
     *
     * <p>{@code from} names the specific {@link InteractionId} the value was read from, not the
     * {@link TestCase} that produced that interaction. Whatever builds this value correctly only ever
     * does so after that interaction's response has actually been read, since the value itself cannot
     * be known any other way - but nothing here enforces that: this type does not stop code from
     * naming an interaction that has not happened yet, which would simply be a mistake with no real
     * data behind it. Naming the interaction rather than the test case is still the better choice for
     * a value built correctly, because it keeps meaning the same thing regardless of whatever RESTest
     * later does with the test case that produced that interaction, such as retrying or repeating it.
     *
     * @param from the interaction this value was read from
     * @param description what was taken from it, for a human to read - "response body field 'id'" -
     *     rather than a machine-readable expression
     */
    record Derived(InteractionId from, String description) implements ValueOrigin {
        public Derived {
            Objects.requireNonNull(from, "from");
            Objects.requireNonNull(description, "description");
            if (description.isBlank()) {
                throw new IllegalArgumentException(
                        "a derived value must say what was taken from " + from);
            }
        }
    }
}
